---
title: "esm_244_final_project"
author: "Anna Calle"
date: "2/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Tab 2: Snowy Plover Data
```{r, message = FALSE, warning=FALSE}
# Load packages and read Snowy Plover csv file

library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(lubridate)
library(sf)
library(leaflet)
library(tmap)
snowyplover <- read_csv("SnowyPlover.csv")

```

## Widget 1: Nest Predation by Year
```{r}
# Count table filtered by specific year
predation <- snowyplover %>% 
  select(year, failure_cause) %>% 
  filter( failure_cause != "NA") %>%
  filter( year == "2015") %>% 
  count(failure_cause, year) %>%
  arrange(-n) %>% 
  mutate( failure_cause = factor(failure_cause, levels = failure_cause))


# Graph using filtered count table
predators_graph <- ggplot(predation, aes( x = failure_cause, y = n)) +
    geom_col() +
      xlab("Cause of Failure") +
      ylab("Number of Affected Nests") +
      scale_y_continuous(expand = c(0,0),limits = c(0,20), breaks = c(0,5,10,15,20)) +
      theme_classic() +
      ggtitle(paste("Causes of Nest Failure at COPR"))+
      theme(plot.title = element_text(hjust = 0.5))

predators_graph

```

## Widget 2: Breeding Data Line Graph

```{r}
# Data wrangling with Snowy Plover breeding data

breeding <- snowyplover %>% 
  select( year, total_eggs, eggs_hatched, chicks_fledged) %>% 
  mutate( nests = 1)
 
# Removing NA, ".", ?, and uncomfirmed
breeding[is.na(breeding)] <- 0
breeding[ breeding == "." | breeding == "unconfirmed" | breeding == "?"] <- 0

# Coerce to numeric class
breeding = as.data.frame(sapply(breeding, as.numeric))

# Creating count table by year and by breeding stage

breeding_table <- breeding %>% 
  group_by(year) %>% 
  summarise( "Nests" = sum(nests), "Eggs Laid" = sum(total_eggs), "Eggs Hatched" = sum(eggs_hatched), "Fledged Chicks" = sum(chicks_fledged)) %>% 
  gather("stage", "count", 2:5)


# Graph
breeding_graph <- ggplot(breeding_table,aes(x = year, y = count, group = stage)) +
        geom_line(aes(color = stage), lwd =1.5) +
        theme_classic() +
        ggtitle(paste("Snowy Plover Breeding Trends at COPR"))+
        theme(plot.title = element_text(hjust = 0.5))+ 
        scale_y_continuous(expand = c(0,0), limits = c(0,200)) +
        scale_x_continuous(expand = c(0,0), breaks = c(2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)) +
        scale_color_manual(values = c("navajowhite3", "skyblue3", "indianred1","lawngreen"))+
        xlab("Year") +
        ylab("Number") +
        labs( color = "Stage")

breeding_graph 
```
###Tab 3: Shorebird Diversity and Abundance  

```{r, message = FALSE, warning=FALSE}

shorebirds <- read_csv("COPR_Shorebird.csv")
#read shorebird data

```

## Widget 1: Bird Diversity by Year
```{r}

#Shorebird abundance by location for 2015

bird_2015 <- shorebirds %>% 
    filter(Year == "2015") %>% #Filter data set by year (use radio buttons or drop down menu to select)
      group_by(Species) %>% 
      count(Polygon_Location, Species)
  
bird_2015_graph <- ggplot(bird_2015, aes(x=Polygon_Location))+
  geom_bar(fill = "navajowhite3")+
  labs(x= "Location", y = "Number Species Observed", title = "Bird Abundance at COPR (2015)")+ 
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(expand = c(0,0), limits = c(0,80), breaks= c(0,20,40,60,80))
   #histogram for locations of where shorebirds were found in beach polygons

bird_2015_graph

```


```{r}
#Shorebird abundance by location for 2016

bird_2016 <- shorebirds %>% 
    filter(Year == "2016") #Filter data set by year (use radio buttons or drop down menu to select)

bird_2016_graph <- ggplot(bird_2016, aes(x=Polygon_Location))+
  geom_bar(fill = "navajowhite3")+
  labs(x= "Location", y = "Number Observed", title = "Bird Abundance at COPR (2016)")+ 
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(expand = c(0,0), limits = c(0,80), breaks= c(0,20,40,60,80)) #histogram for locations of where shorebirds were found in beach polygons
  

bird_2016_graph

```


```{r}

#Shorebird abundance by location for 2017

bird_2017 <- shorebirds %>% 
    filter(Year == "2017") #Filter data set by year (use radio buttons or drop down menu to select)

bird_2017_graph <- ggplot(bird_2015, aes(x=Polygon_Location))+
  geom_bar(fill = "navajowhite3")+
  labs(x= "Location", y = "Number Observed", title = "Bird Abundance at COPR (2017)")+ 
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(expand = c(0,0), limits = c(0,80), breaks= c(0,20,40,60,80))
  #histogram for locations of where shorebirds were found in beach polygons

bird_2017_graph

```

##Widget 2: Top 1- 9 Species of Birds Monthly by Polygon
```{r}
# Wrangling data for top bird species

shorebirds <- read_csv("COPR_Shorebird.csv")
#Converted dates into standard formate
shorebirds$Date <- as.Date(shorebirds$Date, "%m/%d/%Y")

# Top species by year
top_by_year2 <- shorebirds %>%
  mutate( Month = month(Date)) %>%
  select(Month, Year, Species, Count) %>% 
  filter( Year == 2018) %>% 
  group_by(Species) %>% 
  summarize( count = sum(Count)) %>% 
  arrange(-count) %>% 
  head(as.numeric("9"))


# Monthly data filtered for top species by year
top_filtered2 <-  shorebirds %>%
      mutate( Month = month(Date)) %>%
      select(Month, Year, Species, Count) %>% 
      filter( Year == 2018) %>% 
      group_by(Month, Species)%>%
      summarise( count = sum(Count))%>% 
      arrange(Species, -count)

top_filtered2$Month <- as.factor(top_filtered2$Month)#Make month a categorical variable

bird_names2 <- c(   `AMWI` = "American Wigeon",
                   `ANHU` = "Anna's Hummingbird", 
                   `BBPL` = "Black-Bellied Plover",
                    `CALT` = "California Towhee",
                    `HOFI` = "House Finch",
                    `MODO` = "Mourning Dove",
                   `NSHO` = "Northern Shoveler",
                   `RUDO` = "Ruddy Duck",
                    `SAND` = "Sanderling",
                    `SEPL` = "Semipalmated Plover",
                    `SNPL` = "Snowy Plover",
                   `WESA` = "Western Sandpiper",
                    `WILL` = "Willet",
                   `CLSW` = "Cliff Swallow",
                   `SOSP` = "Song Sparrow")#Create facet labels with full bird name

top_graph <- ggplot( top_filtered2[top_filtered2$Species %in% top_by_year2$Species,], aes( x = Month, y = count)) + geom_col(fill = "skyblue3") + 
facet_wrap(~Species, scale = 'free_x', labeller = as_labeller(bird_names2)) +
theme_classic() +
theme(plot.title = element_text(hjust = 0.5)) +
scale_x_discrete(drop = FALSE, breaks = c(1,2,3,4,5,6,7,8,9,10,11,12), labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
scale_y_continuous(expand = c(0, 0), limits=c(0,250))+
labs( y = "Number Observed")

top_graph

```

```{r , message = FALSE, warning=FALSE}
# List of bird codes and names

bird_codes <- shorebirds %>% 
  select(Species) %>% 
  group_by(Species) %>% 
  count() %>% 
  arrange(-n)

bird_names <- read_csv("bird_names.csv")

```


###Tab 1: Creating Map of COPR Polygons

```{r}
# Creating map of the reserve

# Use st_read instad read_csv, st stands for
COPR_polygons <- st_read(dsn = ".", layer = "COPR_polygons-polygon") 

```

```{r}
# Creating labels for polygons
labels <- sprintf(
  "%s",
  COPR_polygons$NAME
) %>% lapply(htmltools::HTML)


leaflet(COPR_polygons) %>% 
      addTiles( group = "Open Street Map") %>%
      addProviderTiles("Esri.WorldImagery", group = "Esri World Imagery") %>%
      addPolygons(weight = 1.0,
                  opacity = 1.0,
                  color = "white",
                  fillOpacity = 0.3,
                  fillColor = topo.colors(12),
                  highlight = highlightOptions(
                    weight = 5,
                    color = "white",
                    fillOpacity = 0.7),
                  group = "Polygons",
                  label = labels,
                  labelOptions = labelOptions(
                    style = list("font-weight" = "normal", padding = "3px 8px"),
                    textsize = "15px",
                    direction = "auto")) %>% 
      addMarkers(lat = 34.411371, lng = -119.876618,
                 label = "Nature Center Coal Oil Point Reserve",
                 group = "Markers") %>% 
      addMarkers(lat = 34.407912, lng = -119.878954,
                 label = "Public Access Sands Beach",
                 group = "Markers") %>% 
  addLayersControl(
    baseGroups = c("Esri World Imagery", "Open Street Map"),
    overlayGroups = c("Polygons", "Markers"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  addEasyButton(easyButton(
    icon="fa-globe", title="Reset zoom",
    onClick=JS("function(btn, map){ map.setZoom(15); }"))) %>% 
  addMiniMap(
    tiles = providers$Esri.WorldImagery,
    toggleDisplay = TRUE,
    position = "bottomleft"
  )
       
    
```



```{r}

shorebirds <- read_csv("COPR_Shorebird.csv")

  shorebirds$Date <- as.Date(shorebirds$Date, "%m/%d/%Y")
  
  # List of top species using selected year input and selected number of species input
  top_by_year <- reactive({
    shorebirds %>%
      mutate( Month = month(Date)) %>%
      select(Month, Year, Species, Count) %>% 
      filter( Year == input$top_year) %>% 
      group_by(Species) %>% 
      summarize( count = sum(Count)) %>% 
      arrange(-count) %>% 
      head(as.numeric(input$top_number)) %>% 
      mutate( Species == as.factor(Species))
  })



 top_filtered <-  reactive({
    shorebirds %>%
      mutate( Month = as.factor(month(Date))) %>%
      select(Month, Year, Species, Count)%>% 
      filter( Year == input$top_year) %>% 
      group_by(Month, Species)%>%
      summarise( count = sum(Count))%>% 
      arrange(Species, -count)
    
    
    
  })
  
  
  # Render column graph
  output$topPlot <- renderPlot({
    
    # Add common name to 4-digit bird watching code
    bird_names2 <- c(   `AMWI` = "American Wigeon",
                        `CAGU`= "California Gull",
                        `ANHU` = "Anna's Hummingbird", 
                        `BBPL` = "Black-Bellied Plover",
                        `CALT` = "California Towhee",
                        `CATE`= "Caspian Tern",
                        `HOFI` = "House Finch",
                        `MODO` = "Mourning Dove",
                        `NSHO` = "Northern Shoveler",
                        `RUDU` = "Ruddy Duck",
                        `SAND` = "Sanderling",
                        `SEPL` = "Semipalmated Plover",
                        `SNPL` = "Snowy Plover",
                        `WCSP`= "White Crowned Sparrow",
                        `WEBL`= "Western Bluebird",
                        `WESA` = "Western Sandpiper",
                        `WILL` = "Willet",
                        `CLSW` = "Cliff Swallow",
                        `SOSP` = "Song Sparrow",
                        `LESA` = "Least Sandpiper")
    
    # Create top species column graph
    ggplot( top_filtered()[top_filtered()$Species %in% top_by_year()$Species,], aes( x = Month, y = count)) +  
      geom_col(fill = "skyblue3") + 
      facet_wrap(~Species, scale = 'free_x', labeller = as_labeller(bird_names2)) +
      theme_classic() +
      theme(plot.title = element_text(hjust = 0.5)) +
      scale_x_discrete( drop = FALSE, breaks = c(1,2,3,4,5,6,7,8,9,10,11,12), labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0,250))+
      labs( y = "Number Observed")+
      ggtitle(paste("Top Bird Species at COPR in Monthly Observations", input$top_year))
  })
```











